name: Manual Deploy to Azure Web App

on:
  workflow_dispatch: # Allows manual triggering

permissions:
  contents: read
  id-token: write # Grant necessary permissions for Azure Login

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }} # Use a single JSON-based secret 

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x

    - name: Install Dependencies
      run: dotnet restore

    # Conditional Build Step (Debug or Release)
    - name: Build
    run: dotnet build --configuration ${{ secrets.BUILD_CONFIGURATION }} --no-restore

    # Conditional Publish Step (Debug or Release)
    - name: Publish
    run: dotnet publish -configuration ${{ secrets.BUILD_CONFIGURATION }} --output ./publish

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: djost-aspnetcore-poc-app
        slot-name: production
        package: ./publish
