name: Manual Deploy to Azure Web App

on:
  workflow_dispatch: # Allows manual triggering

permissions:
  contents: read
  id-token: write # Grant necessary permissions for Azure Login

env:
  BUILD_CONFIGURATION: ${{ secrets.BUILD_CONFIGURATION }} # Global environment variable for build config

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }} # Use a single JSON-based secret 

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x

    - name: Install Dependencies
      run: dotnet restore

    # Build Step (Uses Global Environment Variable - Debug or Release) 
    - name: Build
      run: dotnet build -c $BUILD_CONFIGURATION --no-restore

    # Conditional Publish Step (Debug)
    - name: Publish Debug
      if: env.BUILD_CONFIGURATION == 'Debug'
      run: dotnet publish -c Debug --output ./publish --p:DebugType=full

    # Conditional Publish Step (Release)
    - name: Publish Release
      if: env.BUILD_CONFIGURATION == 'Release'
      run: dotnet publish -c Release --output ./publish
  
    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: djost-aspnetcore-poc-app
        slot-name: production
        package: ./publish
